dtb-$(CONFIG_ARCH_QCOM)	+= apq8016-sbc.dtb msm8916-mtp.dtb msm8952-mtp.dtb \
				qcom-ipq807x-hk01.dtb \
				qcom-ipq807x-hk02.dtb \
				qcom-ipq807x-hk05.dtb \
				qcom-ipq807x-hk06.dtb \
				qcom-ipq807x-db.hk01.dtb \
				qcom-ipq807x-db.hk02.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
